### ISSUE TITLE
version of "socialiteproviders/manager"

### ISSUE THREAD

**Issue by veksa** [jhaoda/socialite-odnoklassniki#13]
this plugin correct work with "socialiteproviders/manager": v2.2.1
i think you can lower the version in composer.json

**Comment by jhaoda** [comment]
Что, даже `v3.0.2` работает с `socialiteproviders/manager: v2.2.1`?

**Comment by veksa** [comment]
да, я проверял работу на v3.0.2, авторизация работает, ошибок нет

**Comment by jhaoda** [comment]
А версия ларвел?

**Comment by veksa** [comment]
5.3.31

**Comment by jhaoda** [comment]
Понятно. Пакет >= 3 сделан под ларавел 5.4, так что если понизить версию менеджера, то на 5.4 не встанет.

**Comment by veksa** [comment]
понятно, тогда я думаю надо добавить фикс в получение настройки для application_key в нижестоящую ветку:

`'application_key' => $this->getConfig('client_public', env('ODNOKLASSNIKI_PUBLIC')),`

т.к. на моем окружении не работает.

**Comment by jhaoda** [comment]
@veksa сделайте PR
