### ISSUE TITLE
L 5.2

### ISSUE THREAD

**Issue by zennokey** [jhaoda/socialite-odnoklassniki#5]
Not work
error:
Driver [odnoklassniki] not supported.

**Comment by jhaoda** [comment]
Почему вы решили, что проблема в пакете?

**Comment by zennokey** [comment]
на более старые версии ставил не раз, а тут ошибка

**Comment by zennokey** [comment]
нашел в чем проблема
вместо 
 SocialiteProviders\Manager\SocialiteWasCalled::class => [
        JhaoDa\SocialiteProviders\Odnoklassniki\OdnoklassnikiExtendSocialite::class
    ],
надо писать
'SocialiteProviders\Manager\SocialiteWasCalled' => [
            'JhaoDa\SocialiteProviders\Odnoklassniki\OdnoklassnikiExtendSocialite@handle'
        ],

**Comment by jhaoda** [comment]
Нет никакой проблемы, это идентичные записи.

**Comment by ishukshin** [comment]
Аналогично была ошибка. Фиксится тем, что классы нужно указывать с первым бэкслешем, иначе неверно понимается. 
```
\SocialiteProviders\Manager\SocialiteWasCalled::class => [
      \JhaoDa\SocialiteProviders\Odnoklassniki\OdnoklassnikiExtendSocialite::class
],
```

На 5.4 это решило проблему
